### ISSUE TITLE
StorageDsc: Converting to new CI pipeline

### ISSUE THREAD

**Issue by johlju** [dsccommunity/StorageDsc#225]
Work need to be done to convert this repository to use the new CI pipeline.

https://dsccommunity.org/blog/convert-a-module-for-continuous-delivery/

**Comment by PlagueHO** [comment]
Hehe these are all duplicates :grin: #223

**Comment by johlju** [comment]
Ah missed the other one! 😄 Then you get to close two issue when you merge 😉 

You can close this as duplicate. :)
