### ISSUE TITLE
Get-DiskByIdentifier: Allow FriendlyName property to be used as a disk identifier

### ISSUE THREAD

**Issue by jambar42** [dsccommunity/StorageDsc#268]
### Problem description

Storage Spaces disks are difficult to define in the configuration with the existing disk identifiers. Please add FriendlyName as a valid disk identifier

See related issue for SerialNumber https://github.com/dsccommunity/StorageDsc/issues/259

### Verbose logs

```text
NA
```

### DSC configuration

```powershell
NA
```

### Suggested solution

Add FriendlyName as a valid Disk Identification property

### Operating system the target node is running

```text
2019
```

### PowerShell version and build the target node is running

```text
5.1
```

### StorageDsc version

```text
5.0.1
```

**Comment by PlagueHO** [comment]
This should be possible. Not too difficult to implement I think as we designed the resource to be flexible on identity of the disk. I'm trying to get back into DSC after next week, so will prioritize this on the backlog.
