### ISSUE TITLE
The deploy fails because there is a space in a tag in the module manifest

### ISSUE THREAD

**Issue by johlju** [dsccommunity/StorageDsc#280]
The deploy fails because there is a space in the tag that was added in this PR. `Dev Drive` should be changed to `DevDrive` in the module manifest (in a new PR): https://github.com/dsccommunity/StorageDsc/pull/278/files#diff-8eee5c09560a979f88c375c8c47f71c0d85a219e61956b96f31efc5988fa2b02R55

See error: https://dev.azure.com/dsccommunity/StorageDsc/_build/results?buildId=8223&view=logs&j=5d0a9c4e-8741-5118-af45-406a30fe661c&t=bda0b158-a237-516f-c1d0-31339587c5b5&l=78

_Originally posted by @johlju in https://github.com/dsccommunity/StorageDsc/issues/276#issuecomment-1783839292_

**Comment by bbonaby** [comment]
Thanks @johlju, thats my bad doing a find and replace. Added update PR to fix this in #281

**Comment by johlju** [comment]
No worries. 🙂  I would have missed this too. We should have a QA test for this, I will suggest that we add one to Sampler, i will add an issue over there too.

**Comment by PlagueHO** [comment]
Thanks @johlju and @bbonaby! I remember seeing this at the time and thinking that it was OK. We should also add the test into DSCResource.Tests
